In [1]:
import numpy as np

In [5]:
Array1 = np.array([11,22,33,44,55])
print(Array1)
print(type(Array1))

[11 22 33 44 55]
<class 'numpy.ndarray'>


In [7]:
list1 = [11,22,33,44,55,66]
print(list1)
print(type(list1))

[11, 22, 33, 44, 55, 66]
<class 'list'>


In [8]:
Array2 = np.asarray(list1)
print(Array2)
print(type(Array2))

[11 22 33 44 55 66]
<class 'numpy.ndarray'>


In [ ]:
Array1 = np.asarray(Array2)

In [9]:
Array1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(Array1)
print(type(Array1))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [15]:
Array2 = np.arange(1,11)
print(Array2)
print(type(Array2))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [20]:
#ones_array = np.array([1,1,1,1,1,1,1,1,1,1])
#ones_array = np.ones((10,))
ones_array = np.ones((3,4),dtype=str)
print(ones_array)
print(type(ones_array))

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
<class 'numpy.ndarray'>


In [22]:
arr = np.array([[11,22],[33,44]])
ones_array = np.ones_like(arr)
print(ones_array)
print(type(ones_array))

[[1 1]
 [1 1]]
<class 'numpy.ndarray'>


In [24]:
#zero_array = np.zeros((10,))
zero_array = np.zeros((10,),dtype=int)
print(zero_array)
print(type(zero_array))

[0 0 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>


In [30]:
arr = np.array(["0","0","0"],dtype=int)
zero_array = np.zeros_like(arr)
print(zero_array)
print(zero_array.dtype)

[0 0 0]
int64


In [31]:
empty_array = np.empty((2,3))
print(empty_array)

[[1.03977794e-312 1.03977794e-312 1.03977794e-312]
 [1.03977794e-312 1.03977794e-312 1.03977794e-312]]


In [32]:
empty_array = np.empty_like(arr)
print(empty_array)

[0 0 0]


In [33]:
eye_array = np.eye(4)
print(eye_array)
print(type(eye_array))
print(eye_array.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>
2


In [35]:
eye_array = np.identity(4)
print(eye_array)
print(type(eye_array))
print(eye_array.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>
2


In [49]:
Array1 = np.array([7,1,5,2,9,23,11,90])
print(Array1)
print(type(Array1))
print(Array1.size)
print(Array1[4])
print(Array1[-2])
#print(Array1[15])
#[start:end:step]
#default start is 0
#default end is size
#default step is 1
print(Array1[2:6])
print(Array1[:6])
print(Array1[2:])
print(Array1[::2])
print(Array1[-2:-6:-1])
print(Array1[::-1])

[ 7  1  5  2  9 23 11 90]
<class 'numpy.ndarray'>
8
9
11
[ 5  2  9 23]
[ 7  1  5  2  9 23]
[ 5  2  9 23 11 90]
[ 7  5  9 11]
[11 23  9  2]
[90 11 23  9  2  5  1  7]


In [6]:
#+ve and -ve indexing on 2-D array
Array1 = np.array([[7,1,4,5],[9,6,12,88],[11,66,22,44],[10,20,40,30]])
print(Array1)
print(Array1[2])
print(Array1[-3])
print(Array1[1,2])#Ar[1][2]
print(Array1[-2,-2])

[[ 7  1  4  5]
 [ 9  6 12 88]
 [11 66 22 44]
 [10 20 40 30]]
[11 66 22 44]
[ 9  6 12 88]
12
22


In [8]:
#+ve and -ve slicing on 2-D array
Array1 = np.array([[7,1,4,5],[9,6,12,88],[11,66,22,44],[10,20,40,30]])
print(Array1[1:3])

print(Array1[1:3,0:3])

print(Array1[:, 2:4])

print(Array1[:, -1:-3:-1])

print(Array1[::2, :])

print(Array1[::2, -1::-1])

[[ 9  6 12 88]
 [11 66 22 44]]
[[ 9  6 12]
 [11 66 22]]
[[ 4  5]
 [12 88]
 [22 44]
 [40 30]]
[[ 5  4]
 [88 12]
 [44 22]
 [30 40]]
[[ 7  1  4  5]
 [11 66 22 44]]
[[ 5  4  1  7]
 [44 22 66 11]]


In [10]:
Array1 = np.arange(1,10)
print(Array1)
print(Array1[3])

[1 2 3 4 5 6 7 8 9]
4


In [14]:
#create an new array with elements. 4, 1, 8
index = np.array([4,1,8])
print(type(index))
#print elements at index 4,1,8 from Array1
print(Array1[index])
#print elements at index 3,1,8,5,1 from Array1
print(Array1[list((3,1,8,5,1))])

<class 'numpy.ndarray'>
[5 2 9]
[4 2 9 6 2]


In [ ]:
#create an new array with elements. 1, 4, 7
index = np.array([1,4,7])
print(type(index))

In [17]:
Array1 = np.arange(1,10)
print(Array1)
#create an new array with elements. 1, 4, 7
index = np.array([1,4,7])
print(type(index))
print(index)
index[1] = 40
print(index)
print(Array1)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[1 4 7]
[ 1 40  7]
[1 2 3 4 5 6 7 8 9]


In [6]:
print(Array1[index])#it retrun elements of Array1 at index 1,4,7

[2 5 8]


In [8]:
Array1 = np.arange(1,16).reshape(5,3)
print(Array1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [10]:
print(Array1[1:3])
idx = np.array([2,0,4])
print(Array1[idx])

[[4 5 6]
 [7 8 9]]
[[ 7  8  9]
 [ 1  2  3]
 [13 14 15]]


In [12]:
Array1 = np.arange(1,50)
print(Array1)
print(Array1[4])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
5


In [14]:
print(Array1%5 == 0)

print(Array1[Array1%5 == 0])

[False False False False  True False False False False  True False False
 False False  True False False False False  True False False False False
  True False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False]


In [19]:
names = np.array(['Akash','Riya','Prakash','Akash','Siya',
                  'akash'])
bool_array = ([names=='Akash'])
print(bool_array)
print(names[names=='Akash'])

[array([ True, False, False,  True, False, False])]
['Akash' 'Akash']


In [34]:
array1 = np.empty((8,8),dtype=int)
for r in range(8):
    array1[r] = r

print(array1)
print(array1[4])
array1[4] = 10
print(array1)

[[0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7]]
[4 4 4 4 4 4 4 4]
[[ 0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3]
 [10 10 10 10 10 10 10 10]
 [ 5  5  5  5  5  5  5  5]
 [ 6  6  6  6  6  6  6  6]
 [ 7  7  7  7  7  7  7  7]]


In [41]:
chessboard = np.zeros((8,8),dtype=int)
print(chessboard)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [42]:
# even_rows = np.array([0,2,4,6])
# odd_rows = np.array([1,3,5,7])
# chessboard[even_rows,1::2] = 1
# chessboard[odd_rows,0::2] = 1
#print(chessboard)

# or

chessboard[0::2,1::2] = 1
chessboard[1::2,0::2] = 1
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [44]:
#arithmetic op. on an array with scalar value
array1 = np.arange(1,10)
print(array1)
array1 = array1+10 # -, *, /, **, //
print(array1)

[1 2 3 4 5 6 7 8 9]
[  1   8  27  64 125 216 343 512 729]


In [45]:
#arithmetic op. on an array with scalar value
array1 = np.arange(1,10).reshape(3,3)
print(array1)
array1 = array1+10 # -, *, /, **, //
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]


In [51]:
#on same shape arrays
array1 = np.arange(1,7).reshape(3,2)
print(array1)
array2 = np.arange(11,17).reshape(3,2)
print(array2)
array3 = array1+array2
print(array3)

[[1 2]
 [3 4]
 [5 6]]
[[11 12]
 [13 14]
 [15 16]]
[[12 14]
 [16 18]
 [20 22]]


In [54]:
array1 = np.arange(1,7).reshape(3,2)
print(array1)
array2 = np.arange(1,4).reshape(3,1)
print(array2)
array3 = array1+array2
print(array3)

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]]
[[2 3]
 [5 6]
 [8 9]]


In [55]:
array1 = np.arange(1,7).reshape(3,2)
print(array1)
array2 = np.arange(1,3).reshape(2,)
print(array2)
array3 = array1+array2
print(array3)

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[[2 4]
 [4 6]
 [6 8]]


2
3
Braodcasting for the arithmetic op. on 2 arrays
array1 (m,n)
second array should be in shape
array2 (m,n)
       (m,1)
       (n,)


In [2]:
a = np.array([True,True,False,False])
b = np.array([True,False,True,False])
c = np.logical_and(a,b)
print(c)
c = np.logical_or(a,b)
print(c)
c = np.logical_not(a)
print(c)
c = np.logical_xor(a,b)
print(c)

[ True False False False]
[ True  True  True False]
[False False  True  True]
[False  True  True False]


In [6]:
#numpy mathematical and statistical functions
array1 = np.arange(1,6)
array2 = np.arange(11,16)
print(array1)
print(array2)
array3 = np.add(array1,array2)
print(array3)
array3 = np.multiply(array1,array2)
print(array3)
array3 = np.subtract(array1,array2)
print(array3)
array3 = np.divide(array1,array2)
print(array3)
# array3 = np.dot(array1,array2)
# print(array3)
newarray = np.sqrt(array1)
print(newarray)
newarray = np.power(array1,2)
print(newarray)

array1 = np.array([8,5,1,5,2,56,1,2,3])
print(array1)
print(np.unique(array1))
print(np.max(array1))
print(np.min(array1))
print(np.argmin(array1))
print(np.argmax(array1))

array3=np.concatenate((array1,array2,array3))
print(array3)

array1 = np.array([8,5,-1,5,2,-56,1,-2,3])
print(array1)
print(np.abs(array1))
print(np.mean(array1))
print(np.median(array1))
print(np.var(array1))

[1 2 3 4 5]
[11 12 13 14 15]
[12 14 16 18 20]
[11 24 39 56 75]
[-10 -10 -10 -10 -10]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]
[ 8  5  1  5  2 56  1  2  3]
[ 1  2  3  5  8 56]
56
1
2
5
[ 8.          5.          1.          5.          2.         56.
  1.          2.          3.         11.         12.         13.
 14.         15.          0.09090909  0.16666667  0.23076923  0.28571429
  0.33333333]
[  8   5  -1   5   2 -56   1  -2   3]
[ 8  5  1  5  2 56  1  2  3]
-3.888888888888889
2.0
348.0987654320988


In [9]:
#numpy character and string functions
array1 = np.array(['aaa','bbb','ccc','dddd'])
array2 = np.array(['ccc','dddd','eee','ffff'])

print(np.char.join(".",array1))

print(np.char.join(".","Hello"))

print(np.char.join([array1,array2],'hell'))

array3 = np.char.add(array1,array2)
print(array3)

array2 = np.array(['Ccc','ddDd','eeE','ffRRff'])
print(np.char.lower(array2))
print(np.char.upper(array2))
print(np.char.center(array2,10,'*'))
print(np.char.split(array2))

print(np.char.replace("Hello Python","Python","Adv Python"))
array1 = np.array(['abc','bcd','cab'])
print(np.char.replace(array1,'b','e'))

['a.a.a' 'b.b.b' 'c.c.c' 'd.d.d.d']
['.' '.' '.' '.']
[['haaaeaaalaaal' 'hbbbebbblbbbl' 'hccceccclcccl' 'hddddeddddlddddl']
 ['hccceccclcccl' 'hddddeddddlddddl' 'heeeeeeeleeel' 'hffffefffflffffl']]
['aaaccc' 'bbbdddd' 'ccceee' 'ddddffff']
['ccc' 'dddd' 'eee' 'ffrrff']
['CCC' 'DDDD' 'EEE' 'FFRRFF']
['***Ccc****' '***ddDd***' '***eeE****' '**ffRRff**']
[list(['Ccc']) list(['ddDd']) list(['eeE']) list(['ffRRff'])]
Hello Adv Python
['aec' 'ecd' 'cae']


In [17]:
print(np.char.equal('Hello','Hello'))
print(np.char.count('hello','l'))
print(np.char.find('hello','a'))
print(np.char.isalpha('hel6lo'))
print(np.char.islower('hello'))
print(np.char.isupper('HI'))

True
2
-1
False
True
True


In [20]:
#numpy set method
array1 = np.arange(1,11)
array2 = np.arange(4,8)
print(array1)
print(array2)

[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6 7]


In [22]:
#print(np.in1d(array2,array1))#check first array is in second array or not
print(np.isin(array2,array1))

[ True  True  True  True]


In [23]:
array1 = np.arange(1,11)
array2 = np.arange(4,15)
print(array1)
print(array2)
print(np.union1d(array1,array2))
print(np.intersect1d(array1,array2))
print(np.setdiff1d(array1,array2))
print(np.setxor1d(array2,array1))


[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 4  5  6  7  8  9 10]
[1 2 3]
[ 1  2  3 11 12 13 14]


In [3]:
import numpy as np
#ones_array = np.array([1,1,1,1,1,1,1,1,1,1])
ones_array = np.ones(10)
print(ones_array)
print(ones_array.ndim)
print(ones_array.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1
(10,)


In [5]:
array1 = np.array([[1,2,3,4],[11,22,33,44],[10,20,30,40]])
print(array1)
print(array1.ndim)
print(array1.shape)
ones_array = np.ones_like(array1)
print(ones_array)
print(ones_array.ndim)
print(ones_array.shape)

[[ 1  2  3  4]
 [11 22 33 44]
 [10 20 30 40]]
2
(3, 4)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
2
(3, 4)


In [9]:
#zeros_array = np.array([0,0,0,0,0])
zeros_array = np.zeros(15)
print(zeros_array)
print(zeros_array.ndim)
print(zeros_array.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
(15,)


In [10]:
array1 = np.array([[1,2,3,4],[11,22,33,44]])
print(array1)
print(array1.ndim)
print(array1.shape)
zeros_array = np.zeros_like(array1)
print(zeros_array)
print(zeros_array.ndim)
print(zeros_array.shape)

[[ 1  2  3  4]
 [11 22 33 44]]
2
(2, 4)
[[0 0 0 0]
 [0 0 0 0]]
2
(2, 4)


In [13]:
empty_array = np.empty(5)
print(empty_array)
print(empty_array.ndim)
print(empty_array.shape)
print(empty_array.size)
print(empty_array.nbytes)

array1 = np.array([[1,2],[11,22],[111,222]])
print(array1)
empty_array = np.empty_like(array1)
print(empty_array)
print(empty_array.ndim)
print(empty_array.shape)
print(empty_array.size)
print(empty_array.nbytes)

[0. 0. 0. 0. 0.]
1
(5,)
5
40
[[  1   2]
 [ 11  22]
 [111 222]]
[[  1   2]
 [ 11  22]
 [111 222]]
2
(3, 2)
6
48


In [15]:
eye_array = np.eye(3)
print(eye_array)

eye_array = np.identity(5)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
array1 = np.arange(1,51)
print(array1)
array1 = np.linspace(1,50,5)
print(array1)
array1 = np.linspace(1,50,3)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[ 1.   13.25 25.5  37.75 50.  ]
[ 1.  25.5 50. ]


In [21]:
Array1 = np.arange(1,51)
print(Array1)
# Bool_Array = Array1%5
Bool_Array = (Array1%5==0)
print(Bool_Array)

print(Array1[Bool_Array])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[False False False False  True False False False False  True False False
 False False  True False False False False  True False False False False
  True False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False  True]
[ 5 10 15 20 25 30 35 40 45 50]


In [33]:
Cities = np.array(["Nashik","Pune","Mumbai","Chennai"])
print(Cities)
# print("i" in "Mumbai")
print(Cities["i" in Cities])

['Nashik' 'Pune' 'Mumbai' 'Chennai']
[]


In [38]:
Chess_Board = np.zeros((8,8),dtype=int)
print(Chess_Board)
Chess_Board[0::2,1::2] = 1
Chess_Board[1::2,0::2] = 1
print(Chess_Board)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [48]:
array1 = np.array([1,2,3])
array2 = np.array([11,22,33])
array3 = array1+array2
print(array1)
print(array2)
print(array3)

[1 2 3]
[11 22 33]
[12 24 36]


In [50]:
array1 = np.array([1,2,3])#(3,)
array2 = np.array([8,5,9]).reshape(3,1)#(3,1)
array3 = array1+array2
print(array1)
print(array2)
print(array3)

[1 2 3]
[[8]
 [5]
 [9]]
[[ 9 10 11]
 [ 6  7  8]
 [10 11 12]]


In [24]:
#Write a NumPy program to create a 3x3 matrix with values 
#ranging from 2 to 10 
array1 = np.arange(2,11).reshape(3,3)
print(array1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [31]:
#Write a NumPy program to generate six random integers between 25 and 55.
array1 = np.linspace(25,55,6,dtype="int")
print(array1)

[25 31 37 43 49 55]


In [33]:
#Write a NumPy program to reverse an array Ar 
array1 = np.array([8,4,7,1,34,2])
print(array1)
print(array1[::-1])

[ 8  4  7  1 34  2]
[ 2 34  1  7  4  8]


In [48]:
'''
Write a NumPy program to append values to the end of an array.  
Expected Output: 
Original array: 
[10, 20, 30]  
After append values to the end of the array: 
[10 20 30 40 50 60 70 80 90] 
'''
array1 = np.array([10, 20, 30])
print(array1)
array2 = np.array([40, 50, 60, 70, 80, 90])
print(array2)
array1 = np.concatenate([array1,array2])
print(array1)


array1 = np.array([10, 20, 30])
print(array1)
data = [40, 50, 60, 70, 80, 90]
print(data)
array1 = np.append(array1,data)
print(array1)

[10 20 30]
[40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]
[10 20 30]
[40, 50, 60, 70, 80, 90]
[10 20 30 40 50 60 70 80 90]


In [51]:
#Write a NumPy program to test whether each element of a 1-D array is also 
#present in a second array 
import numpy as np 
ar1 = np.array([0, 12, 22, 40, 67]) 
print("Array1: ",ar1) 
ar2 = [0, 22] 
print("Array2: ",ar2) 
print("Compare each element of array1 and array2") 
# print(np.in1d(ar1, ar2)) 
print(np.isin(ar2, ar1))

Array1:  [ 0 12 22 40 67]
Array2:  [0, 22]
Compare each element of array1 and array2
[ True  True]


In [52]:
#Write a NumPy program to find the number of elements of an array, 
#length of one array element in bytes and total bytes consumed 
#by the elements 
ar1 = np.array([0, 12, 22, 40, 67]) 
print(ar1.size)
print(ar1.itemsize)
print(ar1.nbytes)

5
8
40
